SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DBTABLE](
	[FIRSTNAME] [varchar](5) NOT NULL,
	[LASTNAME] [varchar](4) NOT NULL,
	[JOBNAME] [varchar](4) NOT NULL,
	[Copied] [bit] NOT NULL,
 CONSTRAINT [PK_DBTABLE] PRIMARY KEY CLUSTERED 
(
	[ICAO_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DBTABLE] ADD  DEFAULT ((0)) FOR [Copied]
GO


